global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alerts/generation_alerts.yml"
  - "alerts/system_alerts.yml"

scrape_configs:
  - job_name: 'synthetic-image-generator'
    static_configs:
      - targets: ['synthetic-image-generator:9090']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

