# Robotics Vertical Configuration

name: "Robotics"
description: "Robot training and human-robot interaction scenarios"

# Supported Scenarios
scenarios:
  manipulation_tasks:
    - object_grasping
    - assembly_operations
    - sorting_tasks
    - precision_placement
    - tool_usage
  
  navigation_tasks:
    - obstacle_avoidance
    - path_planning
    - slam_scenarios
    - multi_robot_coordination
    - dynamic_environments
  
  human_robot_interaction:
    - collaborative_tasks
    - handover_scenarios
    - gesture_recognition
    - voice_interaction
    - safety_zones

# Quality Requirements
quality_metrics:
  manipulation_precision_mm: 0.1
  navigation_accuracy_cm: 1.0
  object_recognition_accuracy: 0.95
  human_detection_accuracy: 0.98
  safety_compliance: 0.99

# Robot Types
robot_types:
  industrial:
    - robotic_arms
    - assembly_robots
    - welding_robots
    - painting_robots
  
  service:
    - cleaning_robots
    - delivery_robots
    - reception_robots
    - medical_assistants
  
  mobile:
    - autonomous_mobile_robots
    - warehouse_robots
    - inspection_robots
    - search_rescue_robots

# Environment Types
environments:
  - factory_floor
  - warehouse
  - office_space
  - home_environment
  - outdoor_terrain
  - laboratory
  - hospital
  - retail_store

# Integration Requirements
integration_requirements:
  ros_compatibility: true
  real_time_control: true
  safety_certified: true
  modular_design: true
