# Quality Thresholds Configuration for Video Synthesis Pipeline

# Video Quality Metrics
video_quality:
  min_resolution: "720p"
  min_fps: 15
  max_compression_ratio: 0.8
  min_bitrate_kbps: 1000
  
  # Advanced quality metrics
  min_psnr_db: 25.0
  min_ssim: 0.8
  max_lpips: 0.3
  min_vmaf: 70.0

# Content Quality Metrics
content_quality:
  min_label_accuracy: 0.92
  max_frame_lag_ms: 300
  min_semantic_consistency: 0.85
  min_object_detection_precision: 0.88
  min_motion_consistency: 0.8
  min_temporal_coherence: 0.75

# Validation Metrics
validation_metrics:
  structural_similarity: 0.7
  perceptual_hash_similarity: 0.6
  motion_consistency: 0.8
  temporal_coherence: 0.75
  color_consistency: 0.8

# Compliance Requirements
compliance:
  privacy_score: 1.0
  bias_detection_threshold: 0.1
  ethical_compliance: true
  gdpr_compliant: true
  hipaa_compliant: false  # Enable for healthcare vertical

# Performance Requirements
performance:
  max_processing_time_minutes: 60
  max_memory_usage_gb: 16
  max_gpu_usage_percent: 85
  min_throughput_videos_per_hour: 10

# Vertical-Specific Overrides
verticals:
  autonomous_vehicles:
    content_quality:
      min_label_accuracy: 0.95
      min_object_detection_precision: 0.95
    performance:
      max_frame_lag_ms: 100
  
  healthcare:
    compliance:
      hipaa_compliant: true
      privacy_score: 1.0
    content_quality:
      min_label_accuracy: 0.99
  
  gaming:
    video_quality:
      min_fps: 60
      min_resolution: "1080p"
    performance:
      max_frame_lag_ms: 16  # 60 FPS
