# Gaming Vertical Configuration

name: "Gaming"
description: "Synthetic video data for game development and testing"

# Supported Scenarios
scenarios:
  gameplay:
    - fps_gameplay
    - racing_gameplay
    - open_world_exploration
    - combat_sequences
    - cutscenes
  
  environments:
    - indoor_environments
    - outdoor_landscapes
    - urban_settings
    - fantasy_worlds
    - sci_fi_environments
  
  character_animations:
    - walking_running
    - combat_movements
    - facial_expressions
    - emotional_reactions
    - physics_interactions
  
  special_effects:
    - explosions
    - weather_effects
    - particle_systems
    - lighting_effects
    - magic_spells

# Quality Requirements
quality_metrics:
  frame_rate_consistency: 0.95
  visual_fidelity: 0.90
  animation_smoothness: 0.92
  physics_accuracy: 0.88
  rendering_performance: 0.85

# Simulation Parameters
simulation_parameters:
  game_engines:
    - unreal
    - unity
    - godot
    - custom_engine
  
  rendering_settings:
    resolution_presets:
      - "1080p"
      - "1440p"
      - "4K"
    
    fps_targets:
      - 30
      - 60
      - 120
      - 144
    
    quality_presets:
      - low
      - medium
      - high
      - ultra
  
  asset_types:
    - characters
    - environments
    - props
    - effects
    - ui_elements

# Procedural Generation
procedural_generation:
  terrain_generation:
    enabled: true
    algorithms:
      - perlin_noise
      - diamond_square
      - voronoi
  
  level_generation:
    enabled: true
    approaches:
      - wave_function_collapse
      - grammar_based
      - agent_based
  
  character_generation:
    enabled: true
    components:
      - body_types
      - facial_features
      - clothing
      - accessories

# Performance Benchmarks
performance_benchmarks:
  target_devices:
    - high_end_pc
    - mid_range_pc
    - console
    - mobile
  
  metrics:
    - fps
    - frame_time
    - memory_usage
    - gpu_utilization
    - cpu_utilization
