name: Continuous Deployment

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]

jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: staging
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to staging
      run: |
        # Update Kubernetes deployment
        kubectl set image deployment/synthetic-image-gen \\
          synthetic-image-gen=your-registry/synthetic-image-gen:${{ github.sha }} \\
          --namespace=staging
        
        # Wait for rollout
        kubectl rollout status deployment/synthetic-image-gen --namespace=staging
    
    - name: Run smoke tests
      run: |
        # Health check
        curl -f http://staging.your-domain.com/health
        
        # Basic functionality test
        python scripts/smoke_tests.py --environment=staging

  deploy-production:
    needs: deploy-staging
    runs-on: ubuntu-latest
    environment: production
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to production
      run: |
        # Blue-green deployment
        helm upgrade --install synthetic-image-gen ./charts \\
          --namespace=production \\
          --set image.tag=${{ github.sha }} \\
          --set environment=production \\
          --wait --timeout=600s
    
    - name: Verify deployment
      run: |
        # Extended health checks
        python scripts/production_verification.py
'''

# ==================== Performance Optimization ====================
performance_optimization = '''
